export const testData = [
    {
        id: 1,
        city: 'b',
        name: 'c',
        totalIncome: 1,
        averageIncome: 2,
        lastMonthIncome: 3,
    },
    {
        id: 2,
        city: 'b',
        name: 'c',
        totalIncome: 1,
        averageIncome: 2,
        lastMonthIncome: 3,
    },
    {
        id: 3,
        city: 'b',
        name: 'c',
        totalIncome: 1,
        averageIncome: 2,
        lastMonthIncome: 3,
    },
    {
        id: 4,
        city: 'b',
        name: 'c',
        totalIncome: 1,
        averageIncome: 2,
        lastMonthIncome: 3,
    },
    {
        id: 5,
        city: 'b',
        name: 'c',
        totalIncome: 1,
        averageIncome: 2,
        lastMonthIncome: 3,
    },
    {
        id: 6,
        city: 'b',
        name: 'c',
        totalIncome: 1,
        averageIncome: 2,
        lastMonthIncome: 3,
    },
];
